In [1]:
!pip install mxnet-cu100

In [0]:
import mxnet as mx
from mxnet import nd, autograd
import matplotlib.pyplot as plt

ctx = mx.gpu()

##Reading the data from text file

In [3]:
with open('text.txt') as file:
    text = file.read()

print(text)

Artificial intelligence (AI) is the simulation of human intelligence processes by machines, especially computer systems. These processes include learning (the acquisition of information and rules for using the information), reasoning (using rules to reach approximate or definite conclusions) and self-correction.
Particular applications of AI include expert systems, speech recognition and machine vision. Artificial intelligence (AI), the ability of a digital computer or computer-controlled robot to perform tasks commonly associated with intelligent beings. The term is frequently applied to the project of developing systems endowed with the intellectual processes characteristic of humans, such as the ability to reason, discover meaning, generalize, or learn from past experience. Since the development of the digital computer in the 1940s, it has been demonstrated that computers can be programmed to carry out very complex tasks—as, for example, discovering proofs for mathematical theorems 

In [4]:
characters = list(set(text))
vocab_length = len(characters)
print(characters)
print(f'Number of unique characters: {vocab_length}')

['K', 'é', 'N', 'a', 'f', 's', ':', 'V', 'O', '”', 'c', '“', 'h', '?', 'b', 'P', 'm', 'G', 'R', 'g', 'd', 'I', 'E', '—', ';', 'A', 'o', '1', 't', 'B', 'M', 'L', 'i', 'D', 'n', 'y', 'T', 'q', 'l', 'S', 'H', 'u', '(', '0', 'j', "'", 'e', 'r', 'p', '.', 'F', '9', '4', 'w', 'k', 'W', '’', 'v', 'C', 'U', ')', 'x', 'z', ' ', ',', '-', '\n']
Number of unique characters: 67


In [5]:
char_to_int = dict([(char, i) for i, char in enumerate(characters)])
char_to_int

{'\n': 66,
 ' ': 63,
 "'": 45,
 '(': 42,
 ')': 60,
 ',': 64,
 '-': 65,
 '.': 49,
 '0': 43,
 '1': 27,
 '4': 52,
 '9': 51,
 ':': 6,
 ';': 24,
 '?': 13,
 'A': 25,
 'B': 29,
 'C': 58,
 'D': 33,
 'E': 22,
 'F': 50,
 'G': 17,
 'H': 40,
 'I': 21,
 'K': 0,
 'L': 31,
 'M': 30,
 'N': 2,
 'O': 8,
 'P': 15,
 'R': 18,
 'S': 39,
 'T': 36,
 'U': 59,
 'V': 7,
 'W': 55,
 'a': 3,
 'b': 14,
 'c': 10,
 'd': 20,
 'e': 46,
 'f': 4,
 'g': 19,
 'h': 12,
 'i': 32,
 'j': 44,
 'k': 54,
 'l': 38,
 'm': 16,
 'n': 34,
 'o': 26,
 'p': 48,
 'q': 37,
 'r': 47,
 's': 5,
 't': 28,
 'u': 41,
 'v': 57,
 'w': 53,
 'x': 61,
 'y': 35,
 'z': 62,
 'é': 1,
 '—': 23,
 '’': 56,
 '“': 11,
 '”': 9}

In [6]:
int_to_char = dict([(i, char) for i, char in enumerate(characters)])
int_to_char

{0: 'K',
 1: 'é',
 2: 'N',
 3: 'a',
 4: 'f',
 5: 's',
 6: ':',
 7: 'V',
 8: 'O',
 9: '”',
 10: 'c',
 11: '“',
 12: 'h',
 13: '?',
 14: 'b',
 15: 'P',
 16: 'm',
 17: 'G',
 18: 'R',
 19: 'g',
 20: 'd',
 21: 'I',
 22: 'E',
 23: '—',
 24: ';',
 25: 'A',
 26: 'o',
 27: '1',
 28: 't',
 29: 'B',
 30: 'M',
 31: 'L',
 32: 'i',
 33: 'D',
 34: 'n',
 35: 'y',
 36: 'T',
 37: 'q',
 38: 'l',
 39: 'S',
 40: 'H',
 41: 'u',
 42: '(',
 43: '0',
 44: 'j',
 45: "'",
 46: 'e',
 47: 'r',
 48: 'p',
 49: '.',
 50: 'F',
 51: '9',
 52: '4',
 53: 'w',
 54: 'k',
 55: 'W',
 56: '’',
 57: 'v',
 58: 'C',
 59: 'U',
 60: ')',
 61: 'x',
 62: 'z',
 63: ' ',
 64: ',',
 65: '-',
 66: '\n'}

In [0]:
def toint(sentence):
    return [char_to_int[char] for char in sentence]

In [0]:
def tosentence(ints):
    return ''.join([int_to_char[_int] for _int in ints])

In [9]:
int_text = toint(text)
int_text

[25,
 47,
 28,
 32,
 4,
 32,
 10,
 32,
 3,
 38,
 63,
 32,
 34,
 28,
 46,
 38,
 38,
 32,
 19,
 46,
 34,
 10,
 46,
 63,
 42,
 25,
 21,
 60,
 63,
 32,
 5,
 63,
 28,
 12,
 46,
 63,
 5,
 32,
 16,
 41,
 38,
 3,
 28,
 32,
 26,
 34,
 63,
 26,
 4,
 63,
 12,
 41,
 16,
 3,
 34,
 63,
 32,
 34,
 28,
 46,
 38,
 38,
 32,
 19,
 46,
 34,
 10,
 46,
 63,
 48,
 47,
 26,
 10,
 46,
 5,
 5,
 46,
 5,
 63,
 14,
 35,
 63,
 16,
 3,
 10,
 12,
 32,
 34,
 46,
 5,
 64,
 63,
 46,
 5,
 48,
 46,
 10,
 32,
 3,
 38,
 38,
 35,
 63,
 10,
 26,
 16,
 48,
 41,
 28,
 46,
 47,
 63,
 5,
 35,
 5,
 28,
 46,
 16,
 5,
 49,
 63,
 36,
 12,
 46,
 5,
 46,
 63,
 48,
 47,
 26,
 10,
 46,
 5,
 5,
 46,
 5,
 63,
 32,
 34,
 10,
 38,
 41,
 20,
 46,
 63,
 38,
 46,
 3,
 47,
 34,
 32,
 34,
 19,
 63,
 42,
 28,
 12,
 46,
 63,
 3,
 10,
 37,
 41,
 32,
 5,
 32,
 28,
 32,
 26,
 34,
 63,
 26,
 4,
 63,
 32,
 34,
 4,
 26,
 47,
 16,
 3,
 28,
 32,
 26,
 34,
 63,
 3,
 34,
 20,
 63,
 47,
 41,
 38,
 46,
 5,
 63,
 4,
 26,
 47,
 63,
 41,
 5,
 32,
 34,
 19,
 63,
 

In [10]:
print(f'Total sequence length of the text: {len(int_text)}')
print(f'First 20 integers: {int_text[:20]}')
print(f'First 20 characters: {tosentence(int_text[:20])}')

Total sequence length of the text: 9792
First 20 integers: [25, 47, 28, 32, 4, 32, 10, 32, 3, 38, 63, 32, 34, 28, 46, 38, 38, 32, 19, 46]
First 20 characters: Artificial intellige


In [0]:
def one_hot(ints, vocab_length = vocab_length):
    outputs = nd.zeros((len(ints), vocab_length))
    for i, idx in enumerate(ints):
        outputs[i, idx] = 1.0
    return outputs

In [12]:
print('Before one hot:')
print(int_text[:20])
print('After one hot:')
print(one_hot(int_text[:20]))

Before one hot:
[25, 47, 28, 32, 4, 32, 10, 32, 3, 38, 63, 32, 34, 28, 46, 38, 38, 32, 19, 46]
After one hot:

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
<NDArray 20x67 @cpu(0)>


In [0]:
def onehot_to_text(embeddings):
    outputs = ""
    ints = nd.argmax(embeddings, axis = 1).asnumpy()
    for i in ints:
        outputs += int_to_char[i]
    return outputs

In [14]:
onehot = one_hot(int_text[:20])
print('First 20 characters in Onehot:')
print(onehot)
print('\nAfter converting First 20 one hot embeddings to text:')
print(f'"{onehot_to_text(onehot)}"')

First 20 characters in Onehot:

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
<NDArray 20x67 @cpu(0)>

After converting First 20 one hot embeddings to text:
"Artificial intellige"


##Building the dataset

In [15]:
seq_length = 32
num_samples = (len(int_text))//seq_length
features = one_hot(int_text[: seq_length * num_samples]).reshape((num_samples, seq_length, vocab_length))
features.shape

(306, 32, 67)

In [16]:
output = onehot_to_text(features[0])
print(output)
print(f'Sequence length: {len(output)}')

Artificial intelligence (AI) is 
Sequence length: 32


In [0]:
def reverse(sentence):
    words = sentence.split(' ')
    words.reverse()
    return ' '.join(words)

In [18]:
reverse('This is seq to seq scratch implementation')

'implementation scratch seq to seq is This'

In [19]:
labels = nd.array([one_hot(toint(reverse(onehot_to_text(sentence)))).asnumpy() for sentence in features])
labels.shape

(306, 32, 67)

In [20]:
print('Original sentence:', onehot_to_text(features[0]))
print('Reversed sentence:', onehot_to_text(labels[0]))

Original sentence: Artificial intelligence (AI) is 
Reversed sentence:  is (AI) intelligence Artificial


In [21]:
batch_size = 8
batches = features.shape[0] // batch_size
print(f'Number of samples in features: {features.shape[0]}')
print(f'Number of batches: {batches}')

Number of samples in features: 306
Number of batches: 38


In [22]:
train_features = features[:batches * batch_size]
print(train_features.shape)
train_features = train_features.reshape((batch_size, batches, seq_length, vocab_length))
print(train_features.shape)
train_features = train_features.swapaxes(0, 1)
print(train_features.shape)
train_features = train_features.swapaxes(1, 2)
print(train_features.shape)

(304, 32, 67)
(8, 38, 32, 67)
(38, 8, 32, 67)
(38, 32, 8, 67)


In [23]:
train_labels = labels[:batches * batch_size]
print(train_labels.shape)
train_labels = train_labels.reshape((batch_size, batches, seq_length, vocab_length))
print(train_labels.shape)
train_labels = train_labels.swapaxes(0, 1)
print(train_labels.shape)
train_labels = train_labels.swapaxes(1, 2)
print(train_labels.shape)

(304, 32, 67)
(8, 38, 32, 67)
(38, 8, 32, 67)
(38, 32, 8, 67)


In [24]:
print(onehot_to_text(train_features[0, :, 0])) # [0(for first batch), :(for all letters in first example), 0(for first example)]
print(onehot_to_text(train_labels[0, :, 0])) # [0(for first batch), :(for all letters in first example), 0(for first example)]

Artificial intelligence (AI) is 
 is (AI) intelligence Artificial


##Defining Encoder Parameters

In [0]:
num_inputs = vocab_length
num_hidden = 512
num_outputs = vocab_length

eWxz = nd.random.normal(shape = (num_inputs, num_hidden), ctx = ctx) * .001
eWxr = nd.random.normal(shape = (num_inputs, num_hidden), ctx = ctx) * .001
eWxh = nd.random.normal(shape = (num_inputs, num_hidden), ctx = ctx) * .001

eWhz = nd.random.normal(shape = (num_hidden, num_hidden), ctx = ctx) * .001
eWhr = nd.random.normal(shape = (num_hidden, num_hidden), ctx = ctx) * .001
eWhh = nd.random.normal(shape = (num_hidden, num_hidden), ctx = ctx) * .001

ebz = nd.random.normal(shape = num_hidden, ctx = ctx) * .001
ebr = nd.random.normal(shape = num_hidden, ctx = ctx) * .001
ebh = nd.random.normal(shape = num_hidden, ctx = ctx) * .001

eWhy = nd.random.normal(shape = (num_hidden,num_outputs), ctx = ctx) * .001
eby = nd.random.normal(shape = num_outputs, ctx = ctx) * .001

encoder_params = [eWxz, eWxr, eWxh, eWhz, eWhr, eWhh, ebz, ebr, ebh, eWhy, eby]

##Defining Encoder

In [0]:
def softmax(linear):
    exp = nd.exp((linear - nd.max(linear, axis = 1).reshape((-1, 1))))
    partition = nd.sum(exp, axis = 1).reshape((-1, 1))
    return exp / partition

In [0]:
def encode(inputs, h):
    outputs = []
    for X in inputs:
        z = nd.sigmoid(nd.dot(X, eWxz) + nd.dot(h, eWhz) + ebz)
        r = nd.sigmoid(nd.dot(X, eWxr) + nd.dot(h, eWhr) + ebr)
        
        g = nd.tanh(nd.dot(X, eWxh) + nd.dot(r * h, eWhh) + ebh)
        h = z * h + (1 - z) * g

        linear = nd.dot(h, eWhy) + eby
        output = softmax(linear)
        outputs.append(output)
    return outputs, h

In [28]:
print(train_features[0].shape)
h = nd.zeros((1, num_hidden)).as_in_context(ctx)
encoded, h = encode(train_features[0].as_in_context(ctx), h)
print(len(encoded), encoded[0].shape)
print(h.shape)

(32, 8, 67)
32 (8, 67)
(8, 512)


##Defining Decoder Parameters

In [0]:
num_inputs = vocab_length
num_hidden = 512
num_outputs = vocab_length

dWxz = nd.random.normal(shape = (num_inputs, num_hidden), ctx = ctx) * .001
dWxr = nd.random.normal(shape = (num_inputs, num_hidden), ctx = ctx) * .001
dWxh = nd.random.normal(shape = (num_inputs, num_hidden), ctx = ctx) * .001

dWhz = nd.random.normal(shape = (num_hidden, num_hidden), ctx = ctx) * .001
dWhr = nd.random.normal(shape = (num_hidden, num_hidden), ctx = ctx) * .001
dWhh = nd.random.normal(shape = (num_hidden, num_hidden), ctx = ctx) * .001

dbz = nd.random.normal(shape = num_hidden, ctx = ctx) * .001
dbr = nd.random.normal(shape = num_hidden, ctx = ctx) * .001
dbh = nd.random.normal(shape = num_hidden, ctx = ctx) * .001

dWhy = nd.random.normal(shape = (num_hidden,num_outputs), ctx = ctx) * .001
dby = nd.random.normal(shape = num_outputs, ctx = ctx) * .001

decoder_params = [dWxz, dWxr, dWxh, dWhz, dWhr, dWhh, dbz, dbr, dbh, dWhy, dby]

## Defining Decoder

In [0]:
def decode(inputs, h):
    outputs = []
    X = inputs[-1]
    for i in range(len(inputs)):
        z = nd.sigmoid(nd.dot(X, dWxz) + nd.dot(h, dWhz) + dbz)
        r = nd.sigmoid(nd.dot(X, dWxr) + nd.dot(h, dWhr) + dbr)
        
        g = nd.tanh(nd.dot(X, dWxh) + nd.dot(r * h, dWhh) + dbh)
        h = z * h + (1 - z) * g

        linear = nd.dot(h, dWhy) + dby
        X = softmax(linear)
        outputs.append(X)
        X = X.argmax(1).one_hot(vocab_length)
    return outputs, h

In [31]:
decoded, h = decode(encoded, h)
print(len(decoded), decoded[0].shape)
print(h.shape)

32 (8, 67)
(8, 512)


In [0]:
def seq_to_seq(inputs, h):
    encoded, h = encode(inputs, h)
    decoded, _ = decode(encoded, h)
    return decoded

##Defining Generator

In [0]:
def generate(prefix):
    string = ''

    int_prefix = [char_to_int[char] for char in prefix]
    input_sequence = one_hot(int_prefix).as_in_context(ctx)

    h = nd.zeros(shape = (1, num_hidden), ctx = ctx)
    
    decoded = seq_to_seq(input_sequence, h)
    
    for d in decoded:
        choice = int(d[0].argmax(0).asscalar())
        string += int_to_char[choice]
    return string

In [34]:
print(generate("Artificial intelligence"))

’’’’’’’’’’’’’’’’’’’’’’’


In [0]:
def cross_entropy(pred, label):
    return -nd.sum(label * nd.log(pred))

In [0]:
def objective(outputs, labels):
    total_loss = 0.
    for (output, label) in zip(outputs,labels):
        total_loss = total_loss + cross_entropy(output, label)
    return total_loss / len(outputs)

In [0]:
params = encoder_params + decoder_params
vs = []
sqrs = []

for param in params:
    param.attach_grad()
    vs.append(param.zeros_like())
    sqrs.append(param.zeros_like())
    
def adam(t, params, vs = vs, sqrs = sqrs, lr = 0.001):
    beta1 = 0.9
    beta2 = 0.999
    eps = 1e-8

    for param, v, sqr in zip(params, vs, sqrs):
        grad = param.grad / batch_size

        v[:] = beta1 * v + (1. - beta1) * grad
        sqr[:] = beta2 * sqr + (1. - beta2) * nd.square(grad + 1e-8)

        v_bias_corr = v / (1. - beta1 ** t)
        sqr_bias_corr = sqr / (1. - beta2 ** t)

        update = lr * v_bias_corr / (nd.sqrt(sqr_bias_corr + 1e-8) + eps)
        param[:] = param - update

In [0]:
def sgd(params, lr):
    for param in params:
        param[:] = param - lr * param.grad

In [39]:
epochs = 200
learning_rate = .001
losses = []

t = 0

for epoch in range(epochs):
    if (epoch + 1) % 50 == 0:
        learning_rate = learning_rate / 1.5
    state = nd.zeros(shape = (batch_size, num_hidden), ctx = ctx)
    for i in range(batches):
        t += 1
        features = train_features[i].as_in_context(ctx)
        labels = train_labels[i].as_in_context(ctx)
        with autograd.record():
            outputs = seq_to_seq(features, state)
            loss = objective(outputs, labels)
            loss.backward()
        adam(t, params, lr = learning_rate)
    losses.append(loss.asscalar())
    print(f'\nEpoch: {epoch} | Loss: {loss.asscalar():.5f}')
    print(generate("Artificial intelligence"))
    print('-'*50)
    print(generate("Research in AI has focused chiefly on"))


Epoch: 0 | Loss: 24.84329
                       
--------------------------------------------------
                                     

Epoch: 1 | Loss: 24.67238
                       
--------------------------------------------------
                                     

Epoch: 2 | Loss: 24.67748
                       
--------------------------------------------------
                                     

Epoch: 3 | Loss: 24.67402
                       
--------------------------------------------------
                                     

Epoch: 4 | Loss: 24.66671
                       
--------------------------------------------------
                                     

Epoch: 5 | Loss: 24.65792
                       
--------------------------------------------------
                                     

Epoch: 6 | Loss: 24.64633
                       
--------------------------------------------------
                                     

Epoch: 7 | Loss: 24

In [40]:
generate('All but the simplest human behaviour is ascribed to intelligence')

'intelligence displipet  th thate teeteeste the eccence  tte hee '

##Lets have some more training here

In [45]:
epochs = 100
learning_rate = .001/1.5/1.5/1.5

for epoch in range(epochs):
    if (epoch + 1) % 50 == 0:
        learning_rate = learning_rate / 1.5
    state = nd.zeros(shape = (batch_size, num_hidden), ctx = ctx)
    for i in range(batches):
        t += 1
        features = train_features[i].as_in_context(ctx)
        labels = train_labels[i].as_in_context(ctx)
        with autograd.record():
            outputs = seq_to_seq(features, state)
            loss = objective(outputs, labels)
            loss.backward()
        adam(t, params, lr = learning_rate)
    losses.append(loss.asscalar())
    print(f'\nEpoch: {epoch} | Loss: {loss.asscalar():.5f}')
    print(generate("Artificial intelligence"))
    print('-'*50)
    print(generate("Research in AI has focused chiefly on"))


Epoch: 0 | Loss: 2.48920
intelligence  irtificia
--------------------------------------------------
gn prasent  ins  ss titmmssssss rfn r

Epoch: 1 | Loss: 2.80859
intelligence dirtiicial
--------------------------------------------------
gn prasett aas  in Rotmtt ass rrnd in

Epoch: 2 | Loss: 3.63204
intelligence  irtiicial
--------------------------------------------------
gn Srasent wiss  sstthhak,, arrrriinc

Epoch: 3 | Loss: 2.29681
Intelligence  irtricial
--------------------------------------------------
gn prasent wass  I  th  sssass, rrrri

Epoch: 4 | Loss: 1.92425
Intelligence iirtiicial
--------------------------------------------------
gn Srasens wass  I  th  ssssas,rrrr i

Epoch: 5 | Loss: 1.67435
intelligence  artiicial
--------------------------------------------------
gn prasent aash io tth ssssss, rrriii

Epoch: 6 | Loss: 1.78172
intelligence  irtiicial
--------------------------------------------------
go prasent ais  AI Rttrtsss as rar rf

Epoch: 7 | Loss: 1.36993
i

KeyboardInterrupt: ignored

In [46]:
generate('All but the simplest human behaviour is ascribed to intelligence')

'intelligenced isplupedt to thed bo elee ieecectthe enesseee, the'

In [47]:
generate('I love AI')

'An Sroje '

In [48]:
generate('Artificial Intelligence')

'Intelligence Aartificia'